# https://github.com/tradichel/2sl-jobexecframework
# resources/ec2/naclrules/RemoteAccessInbound.yaml
# author: @teriradichel @2ndsightlab
##############################################################

Parameters:
  cfparamNetworkAclId:
    Type: String
  cfparamEphemeralPortStart:
    Type: String
    Default: "1024"
  cfparamAllowCidr:
    Type: String
    Default: 0.0.0.0/0
  cfparamSSHInRuleNumber:
    Type: String
    Default: "300"
  cfparamRDPInRuleNumber:
    Type: String
    Default: "301"
  cfparamEphemeralOutRuleNumber:
    Type: String
    Default: "300"

Resources:
  NACLIngress22:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref cfparamAllowCidr
      Egress: False
      NetworkAclId: !Ref cfparamNetworkAclId
      PortRange: 
        From: 22
        To: 22
      Protocol: 6
      RuleAction: Allow
      RuleNumber: !Ref cfparamSSHInRuleNumber

  NACLIngress3389:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref cfparamAllowCidr
      Egress: False
      NetworkAclId: !Ref cfparamNetworkAclId
      PortRange: 
        From: 3389
        To: 3389
      Protocol: 6
      RuleAction: Allow
      RuleNumber: !Ref cfparamRDPInRuleNumber

  NACLEgressEphemeral:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref cfparamAllowCidr
      Egress: True
      NetworkAclId: !Ref cfparamNetworkAclId
      PortRange:
        From: !Ref cfparamEphemeralPortStart
        To: 65535
      Protocol: 6
      RuleAction: Allow
      RuleNumber: !Ref cfparamEphemeralOutRuleNumber


#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################                                             
