# https://github.com/tradichel/2sl-jobexecframework/blob/main/iam/batch_job_role/cfn/role_batch_job.yaml
# IAM/stacks/Role/cfn/GroupRole.yaml
# author: @teriradichel @2ndsightlab
# description: Generic template to create a role for an IAM Group
##############################################################
Parameters:
  cfparamgroupname:
    Type: String
  cfparamgroupusers:
    Type: CommaDelimitedList
  cfparamtimestamp:
    Type: String
    Description: Force an update since AWS overwrites roles and CF doesn't recognize the change

Resources:
  GroupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${cfparamgroupname}Group

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              AWS:
                !Ref cfparamgroupusers
            Condition:
              "Bool":
                "aws:MultiFactorAuthPresent": "true"

Outputs:
  GroupRoleOutput:
    Value: !Ref GroupRole
    Export:
     Name: !Sub ${cfn_groupname_param}RoleExport
  GroupRoleArnOutput:
    Value: !GetAtt GroupRole.Arn
    Export:
     Name: !Sub ${cfparamgroupname}RoleArnExport
  ForceUpdate:
    Value: !Sub "${cfparamtimestamp}"

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 
