# https://github.com/tradichel/2sl-jobexecframework
# IAM/stacks/OkataRole/cfn/Policy/OktaBillingAdminsRolePolicy.yaml
# author: @teriradichel @2ndsightlab
# Description: Deploy okta billing admins policy
# NOTE: This may not work in current form. 
# Need to test update after deploying Okta login.
##############################################################
Resources:
  BillingAdminsOktaRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: BillingAdminsOktaRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'organizations:CreateAccount'
            Resource: '*'
          - Effect: Deny
            Action: 'organizations:*'
            NotResource: !ImportValue DenyAllOUArnExport
          - Effect: Allow
            Action: 
              - 'budgets.*'
              - 'account.*'
              - 'cur.*'
              - 'ce.*'
              - 'freetier.*'
              - 'pricing.*'
            Resource: '*'
          - Effect: Allow
            Action: 'cloudformation:*'
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Billing-*"
              - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Organization-Account-*" 
     Roles:
        - "OktaBillingAdmins"

Outputs:
  OktaPolicyNameOutput:
    Value: BillingAdminsOktaRolePolicy
    Export:
      Name: BillingAdminsOktaRolePolicyPolicyExport

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 

