# https://github.com/tradichel/SecurityMetricsAutomation
# Network/stacks/cfn/NACLrules/HTTPOutbound.yaml
# author: @teriradichel @2ndsightlab
##############################################################
Parameters:

  NetworkAclIdParam:
    Type: String
  EphemeralPortStartParam:
    Type: String
    Default: "1024"
  AllowCidrParam:
    Type: String
    Default: 0.0.0.0/0
  
Resources:

  NACLIngressEphemeral:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref AllowCidrParam
      Egress: False
      NetworkAclId: !Ref NetworkAclIdParam
      PortRange:
        From: !Ref EphemeralPortStartParam
        To: 65535
      Protocol: 6
      RuleAction: Allow
      RuleNumber: 200

  NaclEgress443:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref AllowCidrParam
      Egress: True
      NetworkAclId: !Ref NetworkAclIdParam
      PortRange:
        From: 443
        To: 443
      Protocol: 6
      RuleAction: Allow
      RuleNumber: 201

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 
