# https://github.com/tradichel/2sl-jobexecframework
# awsdeploy/resources/iam/userpolicy/orgadminuserpolicy.yaml
# author: @tradichel @2ndsightlab
# descirption: policy for root-orgadmin user in root-org account
##############################################################
Parameters:
  cfparamName:
    Type: String
    Default: "root-orgadminuserpolicy"
  cfparamManagementAccountId:
    Type: String

Resources:
  Policy:
    Type: AWS::IAM::UserPolicy
    Properties:
      UserName: root-orgadmin
      PolicyName: !Ref cfparamName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowWithoutMFA"
            Effect: Allow
            Action:
              - iam:EnableMFADevice
              - iam:ListMfaDevices
              - iam:GetUser
            Resource:
              !Join
                - ""
                - - !Sub "arn:aws:iam::${AWS::AccountId}:user/"
                  - "${aws:username}"
          - Sid: "GetPasswordPolicy"
            Effect: Allow
            Action: 
              - iam:GetAccountPasswordPolicy
              - iam:ListUsers
              - iam:ListVirtualMFADevices
            Resource: "*"
          - Sid: "VirtualDeviceActionsDoNotIncludeUserResource"
            Effect: Allow
            Action:
              - iam:CreateVirtualMFADevice
              - iam:DeleteVirtualMFADevice
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:mfa/root-orgadmin
          - Sid: "AllowChangeOwnCredentials"
            Effect: Allow
            Action:
              - iam:ChangePassword
              - iam:CreateAccessKey
              - iam:DeactivateMFADevice
              - iam:DeleteAccessKey
              - iam:DeleteVirtualMFADevice
              - iam:Get*
              - iam:List*
              - iam:UpdateAccessKey
            Resource: 
              !Join 
                - ""
                - - !Sub "arn:aws:iam::${AWS::AccountId}:user/"
                  - "${aws:username}"
          - Sid: "AllowAssumeRole"
            Effect: Allow
            Action: sts:assumerole
            Resource: !Sub arn:aws:iam::${cfparamManagementAccountId}:role/root-orgadminrole
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "true"
Outputs:
  PolicyID:
    Value: !Ref Policy
    Export:
     Name: !Sub id-iam-userpolicy-${cfparamName}
  CrossAccountRole:
    Value: !Sub arn:aws:iam::${cfparamManagementAccountId}:role/root-orgadminrole
    Export:
      Name: OrgManagementRole

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
