# https://github.com/tradichel/2sl-jobexecframework
# awsdeploy/resources/iam/userpolicy/usersecretpolicy.yaml
# author: @tradichel @2ndsightlab
# description: CloudFormation template to create an IAM Policy
# that allows users to access a secret with a name that matches
# their own username
##############################################################
Resources:
  Policy:
    Type: AWS::IAM::UserPolicy
    Properties:
      UserName: rootadmin
      PolicyName: rootadminuserpolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

          - Sid: "AllowAllWithMFA"
            Effect: Allow
            Action: '*'
            Resource: '*'
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "true"

          - Sid: "AllowWithoutMFAForAnyResource"
            Effect: Allow
            Action: iam:GetAccountPasswordPolicy
            Resource: '*'

          - Sid: "AllowWithoutMFAForCurrentUser"
            Effect: Allow
            Action:
              - iam:EnableMFADevice
              - iam:ListMfaDevices
              - iam:GetUser
              - iam:ChangePassword #required if you force users to change their password on first use
            Resource: 
              !Sub 'arn:aws:iam::${AWS::AccountId}:user/rootadmin'
          
          - Sid: "OnlyAllowOwnCredentials"
            Effect: Deny
            Action:
              - iam:CreateVirtualMFADevice #device name must match username
              - iam:DeactivateMFADevice #device name must match user name
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:UpdateAccessKey
              - iam:ChangePassword
              - iam:UpdateLoginProfile
            NotResource:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:user/rootadmin'
              - !Sub 'arn:aws:iam::${AWS::AccountId}:mfa/rootadmin'

          - Sid: "DenyTheseActionsMustAssumeRole"
            Effect: Deny
            Action:
              - iam:AttachUserPolicy
              - iam:AttachGroupPolicy
              - iam:CreateUser
              - iam:DetachUserPolicy
              - iam:DeleteUserPermissionsBoundary
              - iam:PutUserPermissionsBoundary
              - iam:PutUserPolicy
              - iam:UpdateUser
              - iam:CreateGroup
              - iam:PassRole
              - iam:CreateInstanceProfile
              - iam:CreateSAML
              - iam:CreateOpenIDConnectProvider
              - iam:PutUserPolicy
              - iam:AddUserToGroup
              - iam:AddRoleToInstanceProfile
              - iam:AddClientIDToOpenIDConnectProvider
            Resource: '*'
          
          - Sid: "DenyModifyOwnRolePermissions"
            Effect: Deny
            Action: 
              - iam:Create*
              - iam:Delete*
              - iam:Update*
              - iam:Put*
              - iam:Attach*
              - iam:Update*
            Resource: 
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/rootadminrole'
              - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/root*'

          - Sid: "AllowGetListOnCloudFormationStacks"
            Effect: Deny
            NotAction:
              - cloudformation:List*
              - cloudformation:Get*
              - cloudformation:Describe*
            Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/root-*'

Outputs:
  PolicyID:
    Value: !Ref Policy
    Export:
     Name: !Sub id-iam-userpolicy-${cfparamName}
  PolicyArn:
    Value: !GetAtt Policy.Arn
    Export:
     Name: !Sub arn-iam-userpolicy-${cfparamName}

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
